### ISSUE TITLE
Got "panic: runtime error: invalid memory address or nil pointer dereference" when running backup

### ISSUE THREAD

**Issue by ntquyen** [tutumcloud/influxdb#57]
I clone this project and build docker image in my local to expose the port 8088 so that I can do backup.

```
$ docker build -t influxdb:0.9.4.2 .
$ docker run -d -p 8083:8083 -p 8086:8086 -p 8088:8088 influxdb:0.9.4.2
$ /opt/influxdb/influxd backup -host 127.0.0.1:8088 /tmp/mysnapshot
```

The command is done successfully but the file is of zero size. The error stacktrace I got from influxdb log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x79a8a8]

goroutine 51 [running]:
github.com/boltdb/bolt.(*DB).beginTx(0x0, 0xc820240000, 0x0, 0x0)
	/tmp/build/src/github.com/boltdb/bolt/db.go:422 +0x2f8
github.com/boltdb/bolt.(*DB).Begin(0x0, 0x0, 0x7fcfe99ce3a8, 0x0, 0x0)
	/tmp/build/src/github.com/boltdb/bolt/db.go:415 +0x60
github.com/influxdb/influxdb/tsdb.appendShardSnapshotFile(0xc8202168a0, 0xc820170fc0, 0xc820181049, 0x13, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/snapshot_writer.go:86 +0x1bd
github.com/influxdb/influxdb/tsdb.appendShardSnapshotFiles(0xc8202168a0, 0xc82016a000, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/snapshot_writer.go:70 +0x669
github.com/influxdb/influxdb/tsdb.NewSnapshotWriter.func1(0xc82015cf00, 0x7e, 0x100, 0xc8202168a0, 0xc82016a000, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/snapshot_writer.go:31 +0x30d
github.com/influxdb/influxdb/tsdb.NewSnapshotWriter(0xc82015cf00, 0x7e, 0x100, 0xc82016a000, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/snapshot_writer.go:20 +0x122
github.com/influxdb/influxdb/services/snapshotter.(*Service).writeSnapshot(0xc8200f48c0, 0x7fcfec82a450, 0xc8200fc338, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/services/snapshotter/service.go:131 +0x1c3
github.com/influxdb/influxdb/services/snapshotter.(*Service).handleConn(0xc8200f48c0, 0x7fcfec82a450, 0xc8200fc338, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/services/snapshotter/service.go:105 +0x1cd
github.com/influxdb/influxdb/services/snapshotter.(*Service).serve.func1(0xc8200f48c0, 0x7fcfec82a450, 0xc8200fc338)
	/tmp/build/src/github.com/influxdb/influxdb/services/snapshotter/service.go:89 +0xbf
created by github.com/influxdb/influxdb/services/snapshotter.(*Service).serve
	/tmp/build/src/github.com/influxdb/influxdb/services/snapshotter/service.go:92 +0x470

goroutine 1 [chan receive]:
main.(*Main).Run(0xc820105f00, 0xc82000a0d0, 0x1, 0x1, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:91 +0xa16
main.main()
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0x29b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:28 +0x37

goroutine 19 [IO wait]:
net.runtime_pollWait(0x7fcfe99d0258, 0x72, 0xc820010140)
	/home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820118530, 0x72, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820118530, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201184d0, 0x0, 0x7fcfec825740, 0xc8201bfd20)
	/home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200fc0c0, 0xc8201bdec8, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8200fc0c0, 0x0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:264 +0x3d
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc820107240, 0x7fcfe99d03e0, 0xc8200fc0c0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:48 +0x4b
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:346 +0xae9

goroutine 20 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200fc0c8, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc820163890, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:2059 +0x51
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc820118540)
	/tmp/build/src/github.com/hashicorp/raft/net_transport.go:346 +0x79
created by github.com/hashicorp/raft.NewNetworkTransport
	/tmp/build/src/github.com/hashicorp/raft/net_transport.go:138 +0x284

goroutine 21 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc820184000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:849 +0xcce
github.com/hashicorp/raft.(*Raft).runLeader(0xc820184000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:821 +0x936
github.com/hashicorp/raft.(*Raft).run(0xc820184000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:602 +0xbb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.run)-fm()
	/tmp/build/src/github.com/hashicorp/raft/raft.go:252 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc820184000, 0xc820168b50)
	/tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 22 [select]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc820184000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:509 +0x10eb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
	/tmp/build/src/github.com/hashicorp/raft/raft.go:253 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc820184000, 0xc820168b60)
	/tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 23 [select]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc820184000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:1636 +0x493
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runSnapshots)-fm()
	/tmp/build/src/github.com/hashicorp/raft/raft.go:254 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc820184000, 0xc820168b70)
	/tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 24 [select]:
github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges(0xc8200f4eb0)
	/tmp/build/src/github.com/influxdb/influxdb/meta/state.go:187 +0x4f5
created by github.com/influxdb/influxdb/meta.(*localRaft).open
	/tmp/build/src/github.com/influxdb/influxdb/meta/state.go:177 +0x1344

goroutine 8 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200fc0d0, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc82011c280)
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:622 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:239 +0x364

goroutine 9 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200fc0d8, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveRPCListener(0xc82011c280)
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:726 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:242 +0x3b6

goroutine 25 [select]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc8201159e0, 0xc82010e6c0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:492 +0x145
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:352 +0xc67

goroutine 26 [select]:
github.com/influxdb/influxdb/monitor.(*Monitor).storeStatistics(0xc82010c750)
	/tmp/build/src/github.com/influxdb/influxdb/monitor/service.go:333 +0x187c
created by github.com/influxdb/influxdb/monitor.(*Monitor).Open
	/tmp/build/src/github.com/influxdb/influxdb/monitor/service.go:134 +0x30c

goroutine 27 [select]:
github.com/influxdb/influxdb/services/hh.(*Service).retryWrites(0xc82012c120)
	/tmp/build/src/github.com/influxdb/influxdb/services/hh/service.go:103 +0x314
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/hh/service.go:67 +0x210

goroutine 28 [select]:
github.com/influxdb/influxdb/services/hh.(*Service).expireWrites(0xc82012c120)
	/tmp/build/src/github.com/influxdb/influxdb/services/hh/service.go:121 +0x2d1
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/hh/service.go:68 +0x232

goroutine 29 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200fc0e0, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/cluster.(*Service).serve(0xc820118380)
	/tmp/build/src/github.com/influxdb/influxdb/cluster/service.go:84 +0xdb
created by github.com/influxdb/influxdb/cluster.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/cluster/service.go:61 +0x135

goroutine 30 [select]:
github.com/influxdb/influxdb/services/precreator.(*Service).runPrecreation(0xc820106d80)
	/tmp/build/src/github.com/influxdb/influxdb/services/precreator/service.go:75 +0x44f
created by github.com/influxdb/influxdb/services/precreator.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/precreator/service.go:53 +0x21f

goroutine 31 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200fc0e8, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/services/snapshotter.(*Service).serve(0xc8200f48c0)
	/tmp/build/src/github.com/influxdb/influxdb/services/snapshotter/service.go:75 +0xa9
created by github.com/influxdb/influxdb/services/snapshotter.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/snapshotter/service.go:48 +0x130

goroutine 32 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200fc0f0, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/services/copier.(*Service).serve(0xc820106e00)
	/tmp/build/src/github.com/influxdb/influxdb/services/copier/service.go:78 +0xa9
created by github.com/influxdb/influxdb/services/copier.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/copier/service.go:51 +0x130

goroutine 33 [IO wait]:
net.runtime_pollWait(0x7fcfe99d0198, 0x72, 0xc820010140)
	/home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201188b0, 0x72, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201188b0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820118850, 0x0, 0x7fcfec825740, 0xc82000bf20)
	/home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200fc168, 0x455470, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8200fc168, 0x0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc820014c60, 0x7fcfe99d03e0, 0xc8200fc168, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1887 +0xb3
net/http.Serve(0x7fcfe99d03e0, 0xc8200fc168, 0x7fcfec8260e8, 0xc82010aa00, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1765 +0x85
github.com/influxdb/influxdb/services/admin.(*Service).serve(0xc8200f49b0)
	/tmp/build/src/github.com/influxdb/influxdb/services/admin/service.go:107 +0x12f
created by github.com/influxdb/influxdb/services/admin.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/admin/service.go:70 +0x491

goroutine 34 [select]:
github.com/influxdb/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc82012c2d0)
	/tmp/build/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:192 +0x565
created by github.com/influxdb/influxdb/services/continuous_querier.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:126 +0x2a4

goroutine 35 [IO wait]:
net.runtime_pollWait(0x7fcfe99d00d8, 0x72, 0xc820010140)
	/home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820118920, 0x72, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820118920, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201188c0, 0x0, 0x7fcfec825740, 0xc82000bf60)
	/home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200fc170, 0x455470, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8200fc170, 0x0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc820014d20, 0x7fcfe99d03e0, 0xc8200fc170, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1887 +0xb3
net/http.Serve(0x7fcfe99d03e0, 0xc8200fc170, 0x7fcfec826110, 0xc820108f00, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1765 +0x85
github.com/influxdb/influxdb/services/httpd.(*Service).serve(0xc82010eb40)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/service.go:133 +0x6e
created by github.com/influxdb/influxdb/services/httpd.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/service.go:101 +0x6ca

goroutine 36 [select]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShardGroups(0xc8200f4b40)
	/tmp/build/src/github.com/influxdb/influxdb/services/retention/service.go:69 +0x351
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x1b4

goroutine 37 [select]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc8200f4b40)
	/tmp/build/src/github.com/influxdb/influxdb/services/retention/service.go:102 +0x7a0
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/retention/service.go:46 +0x1d9

goroutine 38 [chan receive]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).startServerReporting(0xc8201159e0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:443 +0x1eb
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:379 +0x1265

goroutine 39 [select]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).monitorServerErrors(0xc820108180)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:138 +0x2c5
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:120 +0xeeb

goroutine 40 [select, locked to thread]:
runtime.gopark(0xd19f48, 0xc8201a5f28, 0xbd5980, 0x6, 0x18, 0x2)
	/home/philip/.gvm/gos/go1.5/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc8201a5f28, 0x0, 0x18)
	/home/philip/.gvm/gos/go1.5/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc8201a5f28)
	/home/philip/.gvm/gos/go1.5/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/home/philip/.gvm/gos/go1.5/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 49 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc82011e460, 0xc8201fc8a0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627
```

**Comment by fermayo** [comment]
This seems to be an InfluxDB issue. Have you tried sending this to https://github.com/influxdb/influxdb?

**Comment by ntquyen** [comment]
Yeah, it is influxdb issue: https://github.com/influxdb/influxdb/issues/3700. Thanks!
